### ISSUE TITLE
week 2 assignment

### ISSUE THREAD

**Issue by racheliswary** [MrinmoiHossain/Computer-Vision-Coursera#1]
img = imread('image.jpg');

%Get the size (rows and columns) of the image 
[r,c] = size(img);
rr=r/3;
%Wrire code to split the image into three equal parts and store them in B, G, R channels

B=imcrop(img,[1,1,c,rr]);
G=imcrop(img,[1,1*rr,c,rr]);
R=imcrop(img,[1,2*rr,c,rr]);

%concatenate R,G,B channels and assign the RGB image to ColorImg variable
ColorImg(:,:,1) = R;
ColorImg(:,:,2) = G;
ColorImg(:,:,3) = B;
ColorImg = cat(3, R, G, B);
imshow(ColorImg)

error i am getting is 

Validating Blue Channel Image - B
Variable B must be of size [341 400]. It is currently of size [342 400]. Check where the variable is assigned a value.
 similarly for green and red channel.

**Comment by shhankhan81** [comment]
Same error

**Comment by shhankhan81** [comment]
%This is Solution
%Read the image
img = imread('d1.png');
%Get the size (rows and columns) of the image 
[r,c] = size(img);
rr=r/3;
%Wrire code to split the image into three equal parts and store them in B, G, R channels
B=img(1:rr,:);
G=img(rr+1:2*rr,:);
R=img(2*rr+1:r,:);

%concatenate R,G,B channels and assign the RGB image to ColorImg variable
ColorImg(:,:,1)=R;
ColorImg(:,:,2)=G;
ColorImg(:,:,3)=B;
imshow(ColorImg)

**Comment by RDxR10** [comment]
%Solution:
'`img=imread(image.jpg);`

`B = img(1:341,1:1200);`
`G = img(342:682,1:1200);`
`R = img(683:1023,1:1200);`

%concatenate R,G,B channels and assign the RGB image to ColorImg variable
`ColorImg = cat(3, R, G, B);`
